name: Add comment to issue
on:
  issues:
    types:
      - labeled
jobs:
  add-comment-to-issue:
    if: github.event.label.name == 'frontend'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment to issue
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: issue-tracker
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            This issue is available for anyone to work on.
            **Make sure to reference this issue in your pull request.**
            :sparkles: Thank you for your contribution! :sparkles:
