name: Close declined issue
on:
  issues:
    types:
      - labeled
jobs:
  close-declined-issue:
    if: github.event.label.name == 'declined'
    runs-on: ubuntu-latest
    steps:
      - name: Update Issue Status
        uses: octokit/graphql-action@v2.x
        with:
          graphql: |
            mutation ChangeLane($project-number: Int!, $issue-id: ID!, $project-column-name: String!, $project-card-note: String!) {
              moveProjectCard(input: {projectCardId: $issue-id, columnId: $project-column-name, note: $project-card-note}) {
                cardEdge {
                  node {
                    id
                  }
                }
              }
            }
          project-number: 4
          issue-id: ${{ github.event.issue.node_id }}
          project-column-name: "Todo"
          project-card-note: "Issue moved to Todo lane"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
