name: Close declined issue
on:
  issues:
    types:
      - labeled
jobs:
  close-declined-issue:
    if: github.event.label.name == 'declined'
    runs-on: ubuntu-latest
    steps:

      - name: Run gh get projects
        id: gh-projects
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            -X POST \
            -H "Accept: application/vnd.github.inertia-preview+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -F "position=Done" \
            /projects/columns/cards/I_kwDOLkAh0M6EmwE/moves
      - name: Change Status
        run: |
          echo ${{ steps.gh-projects.outputs.data }}
