name: Close declined issue
on:
  issues:
    types:
      - labeled
jobs:
  close-declined-issue:
    if: github.event.label.name == 'declined'
    runs-on: ubuntu-latest
    steps:
      - name: Close issue when declined
        run: |
          gh issue close https://github.com/${{ github.repository }}/issues/${{ github.event.issue.number }}
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
