name: Close declined issue
on:
  issues:
    types:
      - labeled
jobs:
  close-declined-issue:
    if: github.event.label.name == 'declined'
    runs-on: ubuntu-latest
    steps:

      - name: Run gh get projects
        id: gh-projects
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DONE_COLUMN_ID: 98236657
          CARD_ID: I_kwDOLkAh0M6EmwE
        run: |
          gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.WORKFLOW_API_KEY_GITHUB }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /projects/columns/cards/${{ env.CARD_ID }}/moves \
            -F column_id=${{ env.DONE_COLUMN_ID }} \
            -f position='top' 
      - name: Change Status
        run: |
          echo ${{ steps.gh-projects.outputs.data }}
