name: Close declined issue
on:
  issues:
    types:
      - labeled
jobs:
  close-declined-issue:
    if: github.event.label.name == 'declined'
    runs-on: ubuntu-latest
    steps:
      - name: Update Issue Status
        uses: octokit/graphql-action@v2.x
        with:
          graphql: |
            mutation ChangeLane($project_number: Int!, $issue_id: ID!, $project_column_name: String!, $project_card_note: String!) {
              moveProjectCard(input: {projectCardId: $issue_id, columnId: $project_column_name, note: $project_card_note}) {
                cardEdge {
                  node {
                    id
                  }
                }
              }
            }
          project_number: 4
          issue_id: ${{ github.event.issue.node_id }}
          project_column_name: "Todo"
          project_card_note: "Issue moved to Todo lane"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
