name: Close declined issue
on:
  issues:
    types:
      - labeled
jobs:
  close-declined-issue:
    if: github.event.label.name == 'declined'
    runs-on: ubuntu-latest
    steps:

      - name: Remove issue from lane
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DONE_COLUMN_ID: 98236657
          CARD_ID: I_kwDOLkAh0M6EmwE
        run: |
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github.inertia-preview+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Authorization: token ${{ secrets.WORKFLOW_API_KEY_GITHUB }}" \
            /projects/columns/cards/${{ env.CARD_ID }}
      - name: Add issue to new lane
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DONE_COLUMN_ID: 98236657
          CARD_ID: I_kwDOLkAh0M6EmwE
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github.inertia-preview+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Authorization: token ${{ secrets.WORKFLOW_API_KEY_GITHUB }}" \
            /projects/columns/${{ env.DONE_COLUMN_ID }}/cards \
            -F content_id=${{ env.CARD_ID }}
      - name: Change Status
        run: |
          echo ${{ steps.gh-projects.outputs.data }}
