name: Close declined issue
on:
  issues:
    types:
      - opened
      - labeled
jobs:
  close-declined-issue:
    if: github.event.label.name == 'declined'
    runs-on: ubuntu-latest
    steps:
      - name: Close issue
        run: |
          echo ${{ github.workspace }}
          gh issue close https://github.com/${{ env.REPO }}/issues/${{ github.event.issue.number }}
        env:
          REPO: "tapsterbv/issue-tracker"
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
