name: Close declined issue
on:
  issues:
    types:
      - labeled
jobs:
  close-declined-issue:
    if: github.event.label.name == 'declined'
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Project Columns
        id: fetch-columns
        uses: octokit/graphql-action@v2.x
        with:
          graphql: |
            query FetchProjectColumns(project_number: Int!, $repo_owner: String!) {
              organization (login: $repo_owner) {
                project(number: $projectNumber) {
                  columns(first: 100) {
                    nodes {
                      id
                      name
                    }
                  }
                }
              }
            }
          repo_owner: "tapsterbv"
          project_number: 4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Change Status
        run: |
          echo ${{ env.NEWCOLUMNID }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEWCOLUMNID: ${{ fromJson(steps.fetch-columns.outputs.data.repository.project.columns.nodes[?(@.name == 'Todo')].id) }}
