name: Close declined issue
on:
  issues:
    types:
      - opened
      - labeled
jobs:
  close-declined-issue:
    if: github.event.label.name == 'declined'
    runs-on: ubuntu-latest
    steps:
      - name: Close issue
        run: |
          gh issue close https://github.com/tapsterbv/issue-tracker/issues/${{ github.event.issue.number }}
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        working-directory: ${{ github.workspace }}
