name: Close declined issue
on:
  issues:
    types:
      - labeled
jobs:
  close-declined-issue:
    if: github.event.label.name == 'declined'
    runs-on: ubuntu-latest
    steps:
      - name: Update Issue Status
        uses: octokit/graphql-action@v2.x
        with:
          graphql: |
            mutation ChangeLane($projectNumber: Int!, $issueId: ID!, $projectColumnName: String!, $projectCardNote: String!) {
              moveProjectCard(input: {projectCardId: $issueId, columnId: $projectColumnName, note: $projectCardNote}) {
                cardEdge {
                  node {
                    id
                  }
                }
              }
            }
          projectNumber: 4
          issueId: ${{ github.event.issue.node_id }}
          projectColumnName: "Todo"
          projectCardNote: "Issue moved to Todo lane"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
