name: Close declined issue
on:
  issues:
    types:
      - opened
      - labeled
jobs:
  close-declined-issue:
    if: github.event.label.name == 'declined'
    runs-on: ubuntu-latest
    steps:
      - name: Close issue
        run: |
          gh pr close ${{ github.event.issue.number }}
