name: Close declined issue
on:
  issues:
    types:
      - labeled
jobs:
  close-declined-issue:
    if: github.event.label.name == 'declined'
    runs-on: ubuntu-latest
    steps:

      - name: Run gh get projects
        id: gh-projects
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secret.WORKFLOW_API_KEY_GITHUB }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /orgs/tapsterbv/projects
      - name: Change Status
        run: |
          echo ${{ env.NEWCOLUMNID }}
        env:
          NEWCOLUMNID: ${{ fromJson(steps.gh-projects.outputs.data) }}
