name: Close declined issue
on:
  issues:
    types:
      - labeled
jobs:
  close-declined-issue:
    if: github.event.label.name == 'declined'
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Project Columns
        id: fetch-columns
        uses: octokit/graphql-action@v2.x
        with:
          graphql: |
            query GetIssueData {
            	organization(login: ${{ github.event.organization.login }}) {
                project(number: 4) {
                  id
                }
                projectV2(number: 4) {
                  id
                }
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Change Status
        run: |
          echo ${{ env.NEWCOLUMNID }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEWCOLUMNID: ${{ fromJson(steps.fetch-columns.outputs.data) }}
