name: Close declined issue
on:
  issues:
    types:
      - labeled
jobs:
  close-declined-issue:
    if: github.event.label.name == 'declined'
    runs-on: ubuntu-latest
    steps:
      - name: Fetch project information
        uses: actions/github-script@v7
        id: myscript
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          result-encoding: string
          script: |
            github.rest.projects({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
      - name: Change Status
        run: |
          echo ${{ env.NEWCOLUMNID }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEWCOLUMNID: ${{ fromJson(steps.myscript.outputs.data) }}
