name: Close declined issue
on:
  issues:
    types:
      - opened
      - labeled
jobs:
  close-declined-issue:
    if: github.event.label.name == 'declined'
    runs-on: ubuntu-latest
    steps:
      - name: Close issue
        run: |
          echo ${{ github.workspace }}
          echo ${{ github.issue.repo }}
          echo ${{ github.issue.owner }}
        env:
          REPO: "tapsterbv/issue-tracker"
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
