name: Issue handling
on:
  issues:
    types:
      - opened
      - labeled
jobs:
  frontend:
    if: github.event.label.name == 'frontend'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Move issue to frontend
        id: fetch-data
        uses: actions/github-script@v7 
        with:
          github-token: ${{secrets.WORKFLOW_API_KEY_GITHUB}}
          script: |
            const query = `
              mutation AddComment {
                addComment(input:{subjectId: "I_kwDOLkAh0M6DSeXZ", body: "Test"}) {
                  subject {
                    id
                  }
                  subject {
                    id
                  }
                }
              }`;
            const response = await github.graphql(query);
        env:
          GH_GRAPHQL_TOKEN: ${{ secrets.WORKFLOW_API_KEY_GITHUB }}
