name: Issue handling
on:
  issues:
    types:
      - opened
      - labeled
      - edited
      - unlabeled
jobs:
  frontend:
    if: github.event.label.name == 'frontend'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Move issue to frontend
        uses: actions/github-script@v7 
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          DST_REPO: https://github.com/tapsterbv/bambooims-frontend.git
          script: |
            github.rest.issues.update({
              owner: context.repo.owner,
              repo: $DST_REPO,
              issue_number: context.issue.number,
            })
