name: Issue handling
on:
  issues:
    types:
      - opened
      - labeled
jobs:
  frontend:
    if: github.event.label.name == 'frontend'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Fetch data
        id: fetch-data
        uses: octokit/graphql-action@v2.x 
        with:
          GITHUB_TOKEN: ${{secrets.WORKFLOW_API_KEY_GITHUB}}
          query: |
            query FindMutationInfo($owner:String!,$issue_repo:String!,$dst_repo:String!) {
              issueRepo: repository(owner:$owner, name:$issue_repo) {
                issue (number: 2) {
                  id
                }
              }
              dstRepo: repository(owner: $owner, name:$dst_repo) {
                id
              }
            }
          owner: "tapsterbv"
          issue_repo: "issue-tracker"
          dst_repo: "bambooims-frontend"
      - name: Mutate issue
        uses: octokit/graphql-action@v2.x
        with:
          GITHUB_TOKEN: ${{secrets.WORKFLOW_API_KEY_GITHUB}}
          query: |
            mutation TransferIssue {
              transferIssue(input: {issueId: "I_kwDOLkAh0M6DSeXZ", repositoryId: "MDEwOlJlcG9zaXRvcnkxNzc2MjUxMDM="}) {
                issue {
                  url
                  number
                }
              }
            }
