name: Issue handling
on:
  issues:
    types:
      - opened
      - labeled
jobs:
  frontend:
    if: github.event.label.name == 'frontend'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Fetch data
        id: fetch-data
        uses: actions/github-script@v7 
        with:
          github-token: ${{secrets.WORKFLOW_API_KEY_GITHUB}}
          script: |
            return github.graphql(`
              query FindMutationInfo {
              	issueRepo: repository(owner:"tapsterbv", name:"issue-tracker") {
                  issue (number: 2) {
                    id
                  }
                }
                dstRepo: repository(owner: "tapsterbv", name:"bambooims-frontend") {
                  id
                }
              }`)
      - name: Echo query data
        run: |
          echo ${{steps.fetch-data.outputs.result.issueRepo.issue.id}}
          echo ${{steps.fetch-data.outputs.result.dstRepo.id}}
      - name: Mutate issue
        uses: actions/github-script@v7 
        with:
          github-token: ${{secrets.WORKFLOW_API_KEY_GITHUB}}
          script: |
            return github.graphql(`
              mutation TransferIssue {
                transferIssue(input: {issueId: ${{steps.fetch-data.outputs.result.issueRepo.issue.id}}, repositoryId: ${{steps.fetch-data.outputs.result.dstRepo.id}}}) {
                  issue {
                    url
                    number
                  }
                }
              }`)
