name: Issue handling
on:
  issues:
    types:
      - opened
      - labeled
jobs:
  frontend:
    if: github.event.label.name == 'frontend'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Fetch data
        id: fetch-data
        uses: octokit/graphql-action@v2.x 
        with:
          GITHUB_TOKEN: ${{secrets.WORKFLOW_API_KEY_GITHUB}}
          query: |
            query FindMutationInfo($owner:String!,$issue_repo:String!,$dst_repo:String!) {
              issueRepo: repository(owner:$owner, name:$issue_repo) {
                issue (number: 2) {
                  id
                }
              }
              dstRepo: repository(owner: $owner, name:$dst_repo) {
                id
              }
            }
          owner: "tapsterbv"
          issue_repo: "issue-tracker"
          dst_repo: "bambooims-frontend"
      - name: Proces query data
        run: |
          content=`${{steps.fetch-data.outputs.data}}`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=packageJson::$content"
      - name: Echo query data
        run: |
          echo "${{fromJson(steps.set_var.outputs.packageJson).dstRepo.id}}"
      - name: Mutate issue
        uses: octokit/graphql-action@v2.x
        with:
          GITHUB_TOKEN: ${{secrets.WORKFLOW_API_KEY_GITHUB}}
          query: |
            mutation TransferIssue ($issueId: ID!, $repositoryId: ID!) {
              transferIssue(input: {issueId: $issueId, repositoryId: $repositoryId}) {
                issue {
                  url
                  number
                }
              }
          issueId: ""
          repositoryId: ""
