name: Issue handling
on:
  issues:
    types:
      - opened
      - labeled
      - edited
      - unlabeled
jobs:
  frontend:
    if: github.event.label.name == 'frontend'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      actions: write
    steps:
      - name: Move issue to frontend
        uses: actions/github-script@v7 
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: gh issue transfer "$NUMBER" tapsterbv/bambooims-frontend

