name: Issue handling
on:
  issues:
    types:
      - opened
      - labeled
jobs:
  Frontend:
    if: github.event.label.name == 'frontend'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Fetch data
        id: fetch-data
        uses: octokit/graphql-action@v2.x 
        with:
          GITHUB_TOKEN: ${{secrets.WORKFLOW_API_KEY_GITHUB}}
          query: |
            query FindMutationInfo($issue_id: Int!, $owner:String!,$issue_repo:String!,$dst_repo:String!) {
              issueRepo: repository(owner:$owner, name:$issue_repo) {
                issue (number: $issue_id) {
                  id
                }
              }
              dstRepo: repository(owner: $owner, name:$dst_repo) {
                id
              }
            }
          issue_id: ${{ github.event.issue.number }}
          owner: "tapsterbv"
          issue_repo: "issue-tracker"
          dst_repo: "bambooims-frontend"
      - name: Mutate issue
        uses: octokit/graphql-action@v2.x
        with:
          GITHUB_TOKEN: ${{secrets.WORKFLOW_API_KEY_GITHUB}}
          query: |
            mutation TransferIssue ($issue_id: ID!, $repository_id: ID!) {
              transferIssue(input: {issueId: $issue_id, repositoryId: $repository_id}) {
                issue {
                  url
                  number
                }
              }
            }
          issue_id: ${{ fromJson(steps.fetch-data.outputs.data).issueRepo.issue.id }}
          repository_id: ${{ fromJson(steps.fetch-data.outputs.data).dstRepo.id }}
  Backend:
    if: github.event.label.name == 'backend'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Fetch data
        id: fetch-data
        uses: octokit/graphql-action@v2.x 
        with:
          GITHUB_TOKEN: ${{secrets.WORKFLOW_API_KEY_GITHUB}}
          query: |
            query FindMutationInfo($issue_id: Int!, $owner:String!,$issue_repo:String!,$dst_repo:String!) {
              issueRepo: repository(owner:$owner, name:$issue_repo) {
                issue (number: $issue_id) {
                  id
                }
              }
              dstRepo: repository(owner: $owner, name:$dst_repo) {
                id
              }
            }
          issue_id: ${{ github.event.issue.number }}
          owner: "tapsterbv"
          issue_repo: "issue-tracker"
          dst_repo: "tapster-api"
      - name: Mutate issue
        uses: octokit/graphql-action@v2.x
        with:
          GITHUB_TOKEN: ${{secrets.WORKFLOW_API_KEY_GITHUB}}
          query: |
            mutation TransferIssue ($issue_id: ID!, $repository_id: ID!) {
              transferIssue(input: {issueId: $issue_id, repositoryId: $repository_id}) {
                issue {
                  url
                  number
                }
              }
            }
          issue_id: ${{ fromJson(steps.fetch-data.outputs.data).issueRepo.issue.id }}
          repository_id: ${{ fromJson(steps.fetch-data.outputs.data).dstRepo.id }}
