name: Issue handling
on:
  issues:
    types:
      - opened
      - labeled
      - edited
      - unlabeled
jobs:
  frontend:
    if: github.event.label.name == 'frontend'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Move issue to frontend
        run: gh issue transfer "$NUMBER" "$DST_REPO"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          DST_REPO: tapsterbv/bambooims-frontend
          BODY: >
            Dit issue is verplaatst naar de frontend.  
            :sparkles: Het gaat dus opgepakt worden! :sparkles:
