name: Issue handling
on:
  issues:
    types:
      - opened
      - labeled
jobs:
  frontend:
    if: github.event.label.name == 'frontend'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Move issue to frontend
        id: fetch-data
        uses: actions/github-script@v7 
        with:
          github-token: ${{secrets.WORKFLOW_API_KEY_GITHUB}}
          script: |
            const query = `
              query FindMutationInfo {
              	issueRepo: repository(owner:"tapsterbv", name:"issue-tracker") {
                  issue (number: 2) {
                    id
                  }
                }
                dstRepo: repository(owner: "tapsterbv", name:"bambooims-frontend") {
                  id
                }
              }`;
            const response = await github.graphql(query);
            echo response;
        env:
          GH_GRAPHQL_TOKEN: ${{ secrets.WORKFLOW_API_KEY_GITHUB }}
